import type { ReactNode } from "react";
import { Providers } from "./providers"; // <-- 1. Import the client provider
import "./globals.css"; 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body>
      {/* 2. Use the provider, which is a Client Component */}
      <Providers>
        {children}
      </Providers>
    </body>
  </html>
);

