import type { ReactNode } from "react";
import { FogoSessionProvider, Network } from "@fogo/sessions-sdk-react";
import { NATIVE_MINT } from "@solana/spl-token";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import "./globals.css"; 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body>
      <FogoSessionProvider
        network={Network.Testnet}
        
        // --- THIS IS THE FULL FIX ---
        // 1. Add the required sponsor and paymasterUrl from the docs
        sponsor="8HnaXmgFJbvvJxSdjeNyWwMXZb85E35NM4XNg6rxuw3w"
        paymasterUrl="https://sessions-example.fogo.io/paymaster"
        
        // 2. Set the domain to the ONE this test paymaster is
        //    registered to accept, as shown in the example app.
        domain="https://sessions-example.fogo.io"
        
        tokens={[NATIVE_MINT.toBase58(), "fUSDNGgHkZfwckbr5RLLvRbvqvRcTLdH9hcHJiq4jry"]}
        defaultRequestedLimits={{
          [NATIVE_MINT.toBase58()]: 1_500_000_000n,
          "fUSDNGgHkZfwckbr5RLLvRbvqvRcTLdH9hcHJiq4jry": 1_000_000_000n
        }}
        enableUnlimited
      >
        <Navbar />
        <hr />
        <main>
          {children}
        </main>
        <Footer />
      </FogoSessionProvider>
    </body>
  </html>
);

